[package]
name = "rhabarberbar-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["derive"] }
rhabarberbar-core = { path = "../rhabarberbar-core" }

[features]
debug-commands = []

[[bin]]
name = "rhabarberbar"
path = "src/main.rs"
